import type { Tournament, Venue, Sponsor } from "./types";

// รูปฟรีจาก Unsplash (ใช้เป็นภาพประกอบ/แบ็คกราวด์จางๆ ในหน้า SEO)
const IMG = {
  nightStadium: "https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=1600&q=60",
  pitch: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1600&q=60",
  ballGrass: "https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=1600&q=60",
  goal: "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=1600&q=60",
  floodlight: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1600&q=60",
  seats: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1600&q=60",
};

export const seedVenues: Venue[] = [
  { id: "v1", name: "Nongsang Stadium", province: "ชลบุรี", district: "พนัสนิคม", size: "70×50 เมตร (หญ้าจริง)", image_url: IMG.pitch, map_url: "https://maps.google.com/?q=Nongsang+Stadium" },
  { id: "v2", name: "สนามฉ่าปาโมง", province: "กรุงเทพมหานคร", district: "หนองจอก", size: "72×50 เมตร", image_url: IMG.floodlight, map_url: null },
  { id: "v3", name: "สนามหนองละลอก", province: "ระยอง", district: "บ้านค่าย", size: "68×48 เมตร", image_url: IMG.ballGrass, map_url: null },
  { id: "v4", name: "สนามเทศบาลชัยภูมิ", province: "ชัยภูมิ", district: "เมืองชัยภูมิ", size: "หญ้าเทียม", image_url: IMG.goal, map_url: null },
  { id: "v5", name: "สนามกีฬากลางขอนแก่น", province: "ขอนแก่น", district: "เมืองขอนแก่น", size: "มาตรฐาน 11 คน", image_url: IMG.seats, map_url: null },
];

const venueById = (id: string) => seedVenues.find((v) => v.id === id) ?? null;

export const seedTournaments: Tournament[] = [
  {
    id: "t1",
    slug: "nongsang-m7seven-open-cup-2026-1",
    name: "NONGSANG × M7SEVEN OPEN CUP 2026 #1",
    format: "7",
    province: "ชลบุรี",
    team_limit: 32,
    entry_fee: 8000,
    deposit: 1000,
    prize_total: 130000,
    prize_champion: 100000,
    prize_runnerup: 20000,
    prize_third: 5000,
    reg_open: "2026-08-01",
    reg_close: "2026-08-26",
    match_start: "2026-08-29",
    match_end: "2026-08-30",
    status: "live",
    poster_url: null,
    image_url: IMG.nightStadium,
    live_url: "https://www.facebook.com/SRC.Sriracha",
    description:
      "ฟุตบอล 7 คน มาตรฐาน 7 สี ชิงถ้วยท่านสมศักดิ์ เทพสุทิน จับสลากแบ่งสาย 27 ส.ค. 69 เวลา 20.00 น. ผู้ตัดสินระดับไทยลีก T2/T3 แข่งครึ่งเดียว 20 นาที เสมอยิงจุดโทษ 1 คน",
    organizer_name: "เปาต้น วรินทร สัสดี",
    organizer_phone: "064-642-2168",
    organizer_line: "Kruton252629",
    venue_id: "v1",
    venue: venueById("v1"),
  },
  {
    id: "t2",
    slug: "ngoenlaen-chapamong-cup-5",
    name: "เงินแสน ฉ่าปาโมงคัพ ครั้งที่ 5",
    format: "7",
    province: "กรุงเทพมหานคร",
    team_limit: 24,
    entry_fee: 6000,
    deposit: 1000,
    prize_total: 100000,
    prize_champion: 80000,
    prize_runnerup: 15000,
    prize_third: 5000,
    reg_open: "2026-08-05",
    reg_close: "2026-09-08",
    match_start: "2026-09-12",
    match_end: "2026-09-13",
    status: "registering",
    poster_url: null,
    image_url: IMG.floodlight,
    live_url: "https://www.youtube.com/@kwansiri",
    description: "ฟุตบอล 7 คน เงินแสน ชิงแชมป์กรุงเทพฯ เปิดรับ 24 ทีม ทุกระดับ",
    organizer_name: "ทีมงานฉ่าปาโมง",
    organizer_phone: "081-234-5678",
    organizer_line: "chapamong",
    venue_id: "v2",
    venue: venueById("v2"),
  },
  {
    id: "t3",
    slug: "nonglalok-super7-league",
    name: "หนองละลอก ซูเปอร์ 7 ลีก",
    format: "7",
    province: "ระยอง",
    team_limit: 16,
    entry_fee: 4000,
    deposit: 500,
    prize_total: 60000,
    prize_champion: 40000,
    prize_runnerup: 12000,
    prize_third: 4000,
    reg_open: "2026-08-01",
    reg_close: "2026-09-02",
    match_start: "2026-09-06",
    match_end: null,
    status: "closing",
    poster_url: null,
    image_url: IMG.ballGrass,
    live_url: "https://www.facebook.com/meree.live",
    description: "ฟุตบอล 7 คน ระยอง จบใน 1 วัน 16 ทีม นักพากย์เมรีย์แห่งหนองละลอก",
    organizer_name: "เมรีย์ สปอร์ต",
    organizer_phone: "089-111-2222",
    organizer_line: "mereesport",
    venue_id: "v3",
    venue: venueById("v3"),
  },
  {
    id: "t4",
    slug: "larb-chaiyaphum-cup-3",
    name: "ลาบชัยภูมิ คัพ ครั้งที่ 3",
    format: "9",
    province: "ชัยภูมิ",
    team_limit: 20,
    entry_fee: 5000,
    deposit: 1000,
    prize_total: 80000,
    prize_champion: 60000,
    prize_runnerup: 15000,
    prize_third: 5000,
    reg_open: "2026-08-10",
    reg_close: "2026-09-16",
    match_start: "2026-09-20",
    match_end: "2026-09-21",
    status: "registering",
    poster_url: null,
    image_url: IMG.goal,
    live_url: "https://www.youtube.com/@isaansport",
    description: "ฟุตบอล 9 คน อีสาน ชิงถ้วยผู้ว่าฯ 20 ทีม",
    organizer_name: "ลาบชัยภูมิ",
    organizer_phone: "085-333-4444",
    organizer_line: "larbcpm",
    venue_id: "v4",
    venue: venueById("v4"),
  },
  {
    id: "t5",
    slug: "kkc-concrete-champions-cup",
    name: "KKC คอนกรีต แชมเปียนส์ คัพ",
    format: "11",
    province: "ขอนแก่น",
    team_limit: 32,
    entry_fee: 10000,
    deposit: 2000,
    prize_total: 150000,
    prize_champion: 120000,
    prize_runnerup: 20000,
    prize_third: 10000,
    reg_open: "2026-06-01",
    reg_close: "2026-07-20",
    match_start: "2026-07-26",
    match_end: null,
    status: "finished",
    poster_url: null,
    image_url: IMG.seats,
    live_url: null,
    description: "ฟุตบอล 11 คน มาตรฐาน 32 ทีม แชมป์: ทีมไฟใต้ FC",
    organizer_name: "KKC คอนกรีต",
    organizer_phone: "086-555-6666",
    organizer_line: "kkcconcrete",
    venue_id: "v5",
    venue: venueById("v5"),
  },
];

export const seedSponsors: Sponsor[] = [
  { id: "s1", name: "M7 SEVEN", logo_url: null, tier: "platinum", website: "#", active: true },
  { id: "s2", name: "Hi-RUN FURNITURE", logo_url: null, tier: "gold", website: "#", active: true },
  { id: "s3", name: "KKC คอนกรีต", logo_url: null, tier: "gold", website: "#", active: true },
  { id: "s4", name: "AOM WATER", logo_url: null, tier: "standard", website: "#", active: true },
  { id: "s5", name: "ลาบชัยภูมิ", logo_url: null, tier: "standard", website: "#", active: true },
  { id: "s6", name: "เป๋าอ้อย", logo_url: null, tier: "standard", website: "#", active: true },
];
